#!/bin/bash

grunt_plugins=(
    "grunt"
    "grunt-sass"
    "grunt-contrib-watch"
    "grunt-contrib-connect"
    "grunt-contrib-jshint"
    "grunt-contrib-uglify"
    "grunt-contrib-copy"
    "grunt-contrib-imagemin"
    "grunt-notify"
    "grunt-svgstore"
    "load-grunt-config"
    "grunt-browser-sync"
    "grunt-react"
    "grunt-svgmin"
    "grunt-postcss"
    "autoprefixer"
    "git://github.com/sasstools/grunt-sass-lint.git"
    "grunt-contrib-cssmin"
)

bower_plugins=(
    "react"
    "jquery"
    "svg4everybody"
)

if hash grunt 2>/dev/null; then
    echo "==> Grunt already installed."
else
    echo "==> Installing Grunt..."
    npm install -g grunt-cli
fi

if hash bower 2>/dev/null; then
    echo "==> Bower already installed."
else
    echo "==> Installing Bower..."
    npm install -g bower
fi

echo "==> Installing Grunt plugins..."

for i in "${grunt_plugins[@]}"
do
    npm install $i --save-dev
done

echo "==> Installing Bower plugins..."

for i in "${bower_plugins[@]}"
do
    bower install $i --save
done
